#!/bin/bash

# Sprite Session Profile 0
# Default profile for agent 0
# Generated by sprite v0.3.2

# Basic tmux setup for the default agent session
echo "🤖 Configuring sprite session for agent 0 - Basic profile"

# This would normally include actual tmux commands and agent-specific setup
# Placeholder for sprite v0.3.2 package publishing
